"""empty message

Revision ID: 629240ad70f4
Revises: 
Create Date: 2023-04-16 04:16:30.320164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629240ad70f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greeting')
    # ### end Alembic commands ###
